### PR TITLE
New features blog post

### PR DESCRIPTION
**Pull request by yankcrime**
**What this PR does / why we need it**:

Highlight some of the new features that have made it into recent KUDO releases, as it's not always readily apparent from scanning the release notes.

### CODE REVIEW

**Review by mattj-io — APPROVED** [review]

**Review by meichstedt — APPROVED** [review]
Thank you so much @yankcrime <3

preview build seems borked, I'll see if there's anything broken

**Comment by yankcrime** [comment]
Thanks @meichstedt - it previews fine locally so not sure what's broke there.

**Comment by meichstedt** [comment]
@yankcrime figured it our – it was missing a `more` html comment which is used by vuepress to separate excerpt from the rest. Forgot to push and come back to this and just did. Should turn green now and I'll merge once it is!

**Comment by yankcrime** [comment]
Good spot, cheers @meichstedt !

**Pull request merged**
