### PR TITLE
Embed operator docs.

### LINKED ISSUE #152: Spark Runbooks:
* [x] Launch a Spark Job
* [x] Viewing Spark Job output

### PR DESCRIPTION
**Pull request by porridge**
**What this PR does / why we need it**:

This changes the build target to grab a copy of operator docs from GitHub and embed it into the navigation bar.

It's not getting updated in real time, but I think is still better than having to manually copy-paste individual docs. Hopefully it will allow us to survive until @gerred executes his grand plan of moving to GatsbyJS.

**Which issue(s) this PR fixes**:

Fixes #152

**Special notes for your reviewer**:

The spark look ugly but this will soon be fixed by https://github.com/kudobuilder/operators/pull/224

### CODE REVIEW

**Comment by meichstedt** [comment]
Awesome, thank you @porridge!

It would be nice to ensure a meaningful order of the included pages. E.g. for Cassandra docs, _Installing …_ is the 4th entry in the sidebar since the pages are ordered alphabetically.

Also, the Spark docs pages don't have (h1) titles. Can you check w/ @akirillov or @alembiewski as to whether we can adjust them to have proper `# title` markdown? I believe frontmatter would also work; viewpress would pick up this if I'm not mistaken:
```
---
title: My Title
---
…
```

**Comment by porridge** [comment]
> Also, the Spark docs pages don't have (h1) titles.

Plan for this was already mentioned in last paragraph in https://github.com/kudobuilder/kudo.dev/pull/195#issue-373063463
Aaaaand it's merged.

**Comment by porridge** [comment]
> It would be nice to ensure a meaningful order of the included pages.

Hm, I can think of a few solutions for this, none of them great.
Do we care about the relative order of the docs other than putting the one about installation first, @meichstedt ?

**Comment by meichstedt** [comment]
> Do we care about the relative order of the docs other than putting the one about installation first, @meichstedt ?

@porridge the best I can think of is using a frontmatter weight like HUGO uses it. That doesn't affect the filenames, is just metadata, but it's not straightforward to use in bash :)

For now, it might be fine to at least have a common approach at naming: if all installation guides are named _Installing KUDO X_ then it should be easy enough to find that guide.

Out of scope of this PR: we should think about a guideline for operators docs going forwards – like, somehow being a bit ore explicit about which docs are (1) Installation and usage (2) Configuration (3) Troubleshooting (4) Other, like Versions, Release Notes etc. That could be done by naming convention (_How to …_) or …?

**Comment by meichstedt** [comment]
Oh and one thing I forgot to mention: It would be nice to replace all `https://kudo.dev/<relative-link>` with `<relative-link>`. VuePress adds a `target="_blank"` to all fully qualified links 😬

**Comment by porridge** [comment]
@meichstedt the reason I asked specifically about Installation is that I had this hack in mind which I now implemented.
I guess this is good enough for now (until the aforementioned migration to GatsbyJS happens in a few weeks) but if you strongly feel we need a more robust way to sort the navbar, I can take an hour or so to rewrite this script in Python and have it take frontmatter data for sorting.
Please let me know what you think.

**Review by meichstedt — APPROVED** [review]
@porridge thanks, this is good enough for now – meanwhile the spark docs PR has been merged so this looks good now! I'll merge 🚢

**Comment by zmalik** [comment]
This PR removed docs that weren't added later to Kafka
The detailed upgrade runbook or how to debug kafka runbook

**Comment by porridge** [comment]
FTR, @zmalik was kind enough to fix the breakage I did with https://github.com/kudobuilder/operators/pull/235

**Pull request merged**
