### PR TITLE
Added some basic rendering for User's Stories to the landing page

### PR DESCRIPTION
**Pull request by meichstedt**
This is just a draft so we have something to talk about.

### CODE REVIEW

**Comment by mattj-io** [comment]
Do we have a staging site where I can see this ?

**Comment by meichstedt** [comment]
@mattj-io yes, [here](https://deploy-preview-79--kudo-www.netlify.com/#testimonials)

For some reason, the text is rendered twice there – not so for me locally; I'll see why.

**Comment by mattj-io** [comment]
I think these should also be shorter if we want to fit a bunch of them on there - personally I'd cut down this first one to just the second sentence.

**Comment by mattj-io** [comment]
Adding some thoughts here re layout and content. A Github issues template to capture these sounds great - we would need a couple of sentences about the use case, plus a logo. I was thinking having a call to action on the front page saying something like :

"We'd love to hear how you are using KUDO. Tell us your stories by raising a Github issue, and we'll put your logo on the website and send you some exclusive KUDO swag !"

**Comment by mattj-io** [comment]
I don't love the word Testimonials either, not entirely sure why but it always strikes me as a bit corporate. Sorry I don't have any immediate suggestions for a replacement - maybe user stories ?

**Comment by meichstedt** [comment]
> I don't love the word Testimonials either, not entirely sure why but it always strikes me as a bit corporate. Sorry I don't have any immediate suggestions for a replacement - maybe user stories ?

I'm happy to take _User Stories_ for now; then let's change it later if we feel like it :)

**Pull request merged**
